apiVersion: apps/v1
kind: Deployment  # ✅ Capital D
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: ritikpati2/testapp:node02
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT
      
---

apiVersion: v1
kind: Service
metadata:
  name: service-node-app
spec:
  type: LoadBalancer
  selector:
    app: nodedb-app
  ports:
    - name: http
      port: 8080
      targetPort: 3000
