apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc 
spec:
  volumeName: host-pv       # ✅ This correctly binds the PVC to your PV
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
